[package]
name = "amethyst_3d_game"
version = "0.1.0"
authors = ["teng <wwwsousoucom@126.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.amethyst]
version = "0.13"
features = ["vulkan"]
